# This is the input to Dependabot CLI.
# For more examples of what you can do, see the smoke tests: https://github.com/dependabot/smoke-tests/tree/main/tests

job:
  # this is the directory defined in dependabot-core for the ecosystem
  package-manager: github_actions
  allowed-updates:
    - dependency-type: direct
      update-type: all
  source:
    provider: github
    repo: dependabot/example-cli-usage
    directory: "*/**"
    branch: main
  dependency-groups:
    - name: everything
      rules:
        patterns:
          - "*"
# credentials are optional, but are used to authenticate with private repos and registries when provided
credentials:
  - type: git_source
    # Most credentials take a url or host
    host: github.com
    # Credentials will be either username/password or token
    username: x-access-token
    # Dependabot CLI will inject secrets from the environment
    password: $GITHUB_TOKEN
